stages:
  - build
  - docker

build:
  stage: build
  image: golang:1.17-bullseye
  script:
    - go build -trimpath ./cmd/agent
    - go build -trimpath ./cmd/server
  artifacts:
    paths:
      - agent
      - server

agent:
  stage: docker
  script:
    - export DOCKER_BUILDKIT=1
    - echo "$CI_REGISTRY - $CI_PROJECT_PATH"
    - docker logout $CI_REGISTRY
    - docker build -f dockerfiles/agent -t $CI_REGISTRY/zerosrealm/tergum-agent:latest .
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CI_REGISTRY
    - docker image push $CI_REGISTRY/zerosrealm/tergum-agent:latest

server:
  stage: docker
  script:
    - export DOCKER_BUILDKIT=1
    - docker logout $CI_REGISTRY
    - docker build -f dockerfiles/server -t $CI_REGISTRY/zerosrealm/tergum:latest .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker image push $CI_REGISTRY/zerosrealm/tergum:latest

