stages:
  - build
  - docker

build:
  stage: build
  image: golang:1.17-bullseye
  script:
    - go build -trimpath ./cmd/agent
    - go build -trimpath ./cmd/server
  artifacts:
    paths:
      - agent
      - server

server:
  stage: docker
  script:
    - docker logout
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f dockerfiles/server -t $CI_REGISTRY/zerosrealm/tergum:latest .
    - docker image push $CI_REGISTRY/zerosrealm/tergum:latest

agent:
  stage: docker
  script:
    - docker logout
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f dockerfiles/agent -t $CI_REGISTRY/zerosrealm/tergum-agent:latest .
    - docker image push $CI_REGISTRY/zerosrealm/tergum-agent:latest

