stages:
  - build
  - docker

variables:
  server_image: $CI_REGISTRY/zerosrealm/tergum/tergum:latest
  agent_image: $CI_REGISTRY/zerosrealm/tergum/tergum-agent:latest

build:
  stage: build
  image: golang:1.17-bullseye
  only:
    - main
  script:
    - go build -trimpath ./cmd/agent
    - go build -trimpath ./cmd/server
  artifacts:
    paths:
      - agent
      - server

agent:
  stage: docker
  only:
    - main
  script:
    - export DOCKER_BUILDKIT=1
    - docker logout $CI_REGISTRY
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f dockerfiles/agent -t $agent_image .
    - docker image push $agent_image

server:
  stage: docker
  only:
    - main
  script:
    - export DOCKER_BUILDKIT=1
    - docker logout $CI_REGISTRY
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f dockerfiles/server -t $server_image .
    - docker image push $server_image

