stages:
  - build
  - docker

variables:
  server-image: $CI_REGISTRY/zerosrealm/tergum/tergum:latest
  agent-image: $CI_REGISTRY/zerosrealm/tergum/tergum-agent:latest

build:
  stage: build
  image: golang:1.17-bullseye
  script:
    - go build -trimpath ./cmd/agent
    - go build -trimpath ./cmd/server
  artifacts:
    paths:
      - agent
      - server

agent:
  stage: docker
  script:
    - export DOCKER_BUILDKIT=1
    - docker logout $CI_REGISTRY
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f dockerfiles/agent -t $agent-image .
    - docker image push $agent-image

server:
  stage: docker
  script:
    - export DOCKER_BUILDKIT=1
    - docker logout $CI_REGISTRY
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f dockerfiles/server -t $server-image .
    - docker image push $server-image

